version: '3.13.9'


services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000 && python /code/manage.py tailwind start
    volumes:
      - .:/code
    ports:
      - 8000:8000